version: "3.8"

services:
  reverse_proxy:
    image: nginx
    ports:
    - 3214:80   # Opendota
    - 3215:81   # Steam cdn
    volumes:
      # Two dots are the equivalent of './'
      - "../docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "nginx_cache:/data/nginx/cache"

  redis_channels:
    image: redis
    ports:
    - 6379:6379

  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "peers"

volumes:
  nginx_cache:
  postgres_data:
