version: "3.8"

services:
  reverse_proxy:
    image: nginx
    ports:
    - 3214:80
    volumes:
      # Two dots are the equivalent of './'
      - "../docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "nginx_cache:/data/nginx/cache"

  redis_channels:
    image: redis
    ports:
    - 6379:6379

volumes:
  nginx_cache:
