# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PeerData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PeerData.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ePeerData.proto\"4\n\x08Metadata\x12\x0f\n\x05start\x18\x01 \x01(\x08H\x00\x12\r\n\x03\x65nd\x18\x02 \x01(\x08H\x00\x42\x08\n\x06Status\"7\n\x04Peer\x12\x12\n\naccountId2\x18\x01 \x01(\x05\x12\r\n\x05games\x18\x02 \x01(\x05\x12\x0c\n\x04wins\x18\x03 \x01(\x05\"!\n\x0cPeersRequest\x12\x11\n\taccountId\x18\x01 \x01(\x05\"8\n\rPeersResponse\x12\x11\n\taccountId\x18\x01 \x01(\x05\x12\x14\n\x05peers\x18\x02 \x03(\x0b\x32\x05.Peer\"7\n\x07\x41vatars\x12\r\n\x05small\x18\x01 \x01(\t\x12\x0e\n\x06medium\x18\x02 \x01(\t\x12\r\n\x05large\x18\x03 \x01(\t\"\"\n\rPlayerRequest\x12\x11\n\taccountId\x18\x01 \x01(\x05\"\xdf\x01\n\x0ePlayerResponse\x12\x11\n\taccountId\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x12\x10\n\x08\x64otaPlus\x18\x04 \x01(\x08\x12\x0f\n\x07steamId\x18\x05 \x01(\t\x12\x19\n\x07\x61vatars\x18\x06 \x01(\x0b\x32\x08.Avatars\x12\x12\n\nprofileUrl\x18\x07 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x08 \x01(\t\x12\x0c\n\x04wins\x18\t \x01(\x05\x12\r\n\x05loses\x18\n \x01(\x05\x12\x16\n\x0eprofilePicture\x18\x0b \x01(\x0c\"z\n\x0fPeerDataRequest\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1f\n\x07players\x18\x02 \x03(\x0b\x32\x0e.PlayerRequest\x12\x1c\n\x05peers\x18\x03 \x03(\x0b\x32\r.PeersRequest\x12\x1b\n\x08metadata\x18\x04 \x01(\x0b\x32\t.Metadata\"`\n\x10PeerDataResponse\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12 \n\x07players\x18\x02 \x03(\x0b\x32\x0f.PlayerResponse\x12\x1d\n\x05peers\x18\x03 \x03(\x0b\x32\x0e.PeersResponseb\x06proto3'
)




_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Metadata.start', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='Metadata.end', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Status', full_name='Metadata.Status',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=18,
  serialized_end=70,
)


_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountId2', full_name='Peer.accountId2', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='games', full_name='Peer.games', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wins', full_name='Peer.wins', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=127,
)


_PEERSREQUEST = _descriptor.Descriptor(
  name='PeersRequest',
  full_name='PeersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountId', full_name='PeersRequest.accountId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=162,
)


_PEERSRESPONSE = _descriptor.Descriptor(
  name='PeersResponse',
  full_name='PeersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountId', full_name='PeersResponse.accountId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peers', full_name='PeersResponse.peers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=220,
)


_AVATARS = _descriptor.Descriptor(
  name='Avatars',
  full_name='Avatars',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='small', full_name='Avatars.small', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medium', full_name='Avatars.medium', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='large', full_name='Avatars.large', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=277,
)


_PLAYERREQUEST = _descriptor.Descriptor(
  name='PlayerRequest',
  full_name='PlayerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountId', full_name='PlayerRequest.accountId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=313,
)


_PLAYERRESPONSE = _descriptor.Descriptor(
  name='PlayerResponse',
  full_name='PlayerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountId', full_name='PlayerResponse.accountId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='PlayerResponse.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='PlayerResponse.rank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dotaPlus', full_name='PlayerResponse.dotaPlus', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steamId', full_name='PlayerResponse.steamId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avatars', full_name='PlayerResponse.avatars', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profileUrl', full_name='PlayerResponse.profileUrl', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='countryCode', full_name='PlayerResponse.countryCode', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wins', full_name='PlayerResponse.wins', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loses', full_name='PlayerResponse.loses', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profilePicture', full_name='PlayerResponse.profilePicture', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=539,
)


_PEERDATAREQUEST = _descriptor.Descriptor(
  name='PeerDataRequest',
  full_name='PeerDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PeerDataRequest.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='players', full_name='PeerDataRequest.players', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peers', full_name='PeerDataRequest.peers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='PeerDataRequest.metadata', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=663,
)


_PEERDATARESPONSE = _descriptor.Descriptor(
  name='PeerDataResponse',
  full_name='PeerDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PeerDataResponse.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='players', full_name='PeerDataResponse.players', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peers', full_name='PeerDataResponse.peers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=761,
)

_METADATA.oneofs_by_name['Status'].fields.append(
  _METADATA.fields_by_name['start'])
_METADATA.fields_by_name['start'].containing_oneof = _METADATA.oneofs_by_name['Status']
_METADATA.oneofs_by_name['Status'].fields.append(
  _METADATA.fields_by_name['end'])
_METADATA.fields_by_name['end'].containing_oneof = _METADATA.oneofs_by_name['Status']
_PEERSRESPONSE.fields_by_name['peers'].message_type = _PEER
_PLAYERRESPONSE.fields_by_name['avatars'].message_type = _AVATARS
_PEERDATAREQUEST.fields_by_name['players'].message_type = _PLAYERREQUEST
_PEERDATAREQUEST.fields_by_name['peers'].message_type = _PEERSREQUEST
_PEERDATAREQUEST.fields_by_name['metadata'].message_type = _METADATA
_PEERDATARESPONSE.fields_by_name['players'].message_type = _PLAYERRESPONSE
_PEERDATARESPONSE.fields_by_name['peers'].message_type = _PEERSRESPONSE
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['Peer'] = _PEER
DESCRIPTOR.message_types_by_name['PeersRequest'] = _PEERSREQUEST
DESCRIPTOR.message_types_by_name['PeersResponse'] = _PEERSRESPONSE
DESCRIPTOR.message_types_by_name['Avatars'] = _AVATARS
DESCRIPTOR.message_types_by_name['PlayerRequest'] = _PLAYERREQUEST
DESCRIPTOR.message_types_by_name['PlayerResponse'] = _PLAYERRESPONSE
DESCRIPTOR.message_types_by_name['PeerDataRequest'] = _PEERDATAREQUEST
DESCRIPTOR.message_types_by_name['PeerDataResponse'] = _PEERDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:Metadata)
  })
_sym_db.RegisterMessage(Metadata)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
  'DESCRIPTOR' : _PEER,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:Peer)
  })
_sym_db.RegisterMessage(Peer)

PeersRequest = _reflection.GeneratedProtocolMessageType('PeersRequest', (_message.Message,), {
  'DESCRIPTOR' : _PEERSREQUEST,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:PeersRequest)
  })
_sym_db.RegisterMessage(PeersRequest)

PeersResponse = _reflection.GeneratedProtocolMessageType('PeersResponse', (_message.Message,), {
  'DESCRIPTOR' : _PEERSRESPONSE,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:PeersResponse)
  })
_sym_db.RegisterMessage(PeersResponse)

Avatars = _reflection.GeneratedProtocolMessageType('Avatars', (_message.Message,), {
  'DESCRIPTOR' : _AVATARS,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:Avatars)
  })
_sym_db.RegisterMessage(Avatars)

PlayerRequest = _reflection.GeneratedProtocolMessageType('PlayerRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERREQUEST,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:PlayerRequest)
  })
_sym_db.RegisterMessage(PlayerRequest)

PlayerResponse = _reflection.GeneratedProtocolMessageType('PlayerResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERRESPONSE,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:PlayerResponse)
  })
_sym_db.RegisterMessage(PlayerResponse)

PeerDataRequest = _reflection.GeneratedProtocolMessageType('PeerDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _PEERDATAREQUEST,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:PeerDataRequest)
  })
_sym_db.RegisterMessage(PeerDataRequest)

PeerDataResponse = _reflection.GeneratedProtocolMessageType('PeerDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _PEERDATARESPONSE,
  '__module__' : 'PeerData_pb2'
  # @@protoc_insertion_point(class_scope:PeerDataResponse)
  })
_sym_db.RegisterMessage(PeerDataResponse)


# @@protoc_insertion_point(module_scope)
